language: python
python:
 - "3.8"
cache: pip
addons:
 firefox: latest
before_install:
 - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
 - mkdir geckodriver
 - tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
 - export PATH=$PATH:$PWD/geckodriver
 - geckodriver --version
 - export MOZ_HEADLESS=1
install:
 - pip install -r requirements.txt
before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 # give xvfb some time to start
script:
 - python manage.py makemigrations
 - python manage.py migrate
 - python manage.py test functional_test
sudo: false
dist: xenial
services:
  - xvfb
